import Head from "next/head";
import MainLayout from "../components/layout";
import { ThemeProvider } from "next-themes";

import "bootstrap/dist/css/bootstrap.min.css";
import "../styles/fonts.sass";
import "../styles/global.sass";

type Props = {
  Component: any;
  pageProps: any;
};

function MyApp({ Component, pageProps }: Props) {
  return (
    <>
      <Head>
        <title>Axies | NFT Marketplace Next JS Template</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/static/assets/images/fire-logo.jpg" /> */}
      </Head>
      <ThemeProvider defaultTheme={"dark"} enableSystem={false}>
        <MainLayout>
          <Component {...pageProps} />
        </MainLayout>
      </ThemeProvider>
    </>
  );
}

export default MyApp;
